package com.example.teacher.ui.navigation

object Routes {
    const val Onboarding = "onboarding"
    const val Welcome = "welcome"
    const val LoginRoleSelection = "login_role_selection"
    const val RegisterRoleSelection = "register_role_selection"
    const val RoleSelection = "role_selection"
    const val GuestHome = "guest_home"

    const val LoginTabs = "login_tabs"
    fun loginTabs(role: String) = "$LoginTabs/$role"

    const val ParentLogin = "parent_login"
    const val ParentRegister = "parent_register"
    const val ParentHome = "parent_home"
    const val ParentMessages = "parent_messages"
    const val ParentPublish = "parent_publish"
    const val ReportSubmit = "report_submit"
    fun reportSubmit(role: String) = "$ReportSubmit/$role"
    const val ParentMe = "parent_me"
    const val ParentProfile = "parent_profile"
    const val TeacherList = "teacher_list"
    const val TeacherSearch = "teacher_search"
    const val TeacherDetail = "teacher_detail"
    const val ParentApplications = "parent_applications"
    const val Payment = "payment"
    const val Chat = "chat"

    const val Products = "products"
    const val ProductSearch = "product_search"
    const val ProductDetail = "product_detail"
    const val Cart = "cart"
    const val Orders = "orders"
    const val OrderDetail = "order_detail"

    const val TeacherLogin = "teacher_login"
    const val TeacherRegister = "teacher_register"
    const val TeacherHome = "teacher_home"
    const val TeacherDemands = "teacher_demands"
    const val TeacherStudents = "teacher_students"
    const val TeacherCourses = "teacher_courses"
    const val TeacherMe = "teacher_me"
    const val TeacherPublicProfile = "teacher_public_profile"
    const val TeacherIncome = "teacher_income"
    const val TeacherNotifications = "teacher_notifications"
    const val TeacherProfile = "teacher_profile"
    const val TeacherApplications = "teacher_applications"

    const val AdminLogin = "admin_login"
    const val AdminDashboard = "admin_dashboard"
    const val AdminUsers = "admin_users"
    const val AdminTeacherReview = "admin_teacher_review"
    const val AdminOrders = "admin_orders"
    const val AdminReports = "admin_reports"
    const val AdminStats = "admin_stats"
    const val AdminParents = "admin_parents"
    const val AdminTeachers = "admin_teachers"
    const val AdminApplications = "admin_applications"
    const val AdminPayments = "admin_payments"
    const val AdminProducts = "admin_products"

    fun teacherDetail(teacherId: Int) = "$TeacherDetail/$teacherId"
    fun payment(applicationId: Int) = "$Payment/$applicationId"
    fun chat(applicationId: Int) = "$Chat/$applicationId"
    fun productDetail(productId: Int) = "$ProductDetail/$productId"
    fun orderDetail(orderId: Int) = "$OrderDetail/$orderId"
}
